@startuml ContainerDiagram
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

!define DEVICONS https://raw.githubusercontent.com/tupadr3/plantuml-icon-font-sprites/master/devicons
!define FONTAWESOME https://raw.githubusercontent.com/tupadr3/plantuml-icon-font-sprites/master/font-awesome-5
!include DEVICONS/angular.puml
!include DEVICONS/java.puml
!include DEVICONS/msql_server.puml
!include FONTAWESOME/users.puml

Person(delegate, "Delegate", "Attends the conference")
Person(exhibitor, "Exhibitor", "Exhibits at the conference")
Person(speaker, "Speaker", "Speaks at the conference")
Person(admin, "Admin", "Manages the conference")
Person(analyst, "Analyst", "Produces reports, analyses data from events")

Container(CDN, "Content Delivery Network", "CDN Providers", "Cache static content")
System(spaApplication, "Single Page Web Application", "Single Page Application, ran on the browser")
System(mobileApplication, "mobileApplication", "BMI2 application on mobile")
Container(webApplication, "webApplication", "Delivers the static content, and SPA application")
Container(backend, "Backend", "Backend application", "REST APIs, handle business logic")
ContainerDb(database, "Database", "Datastores for the backend APIs")
Container(domainEvents, "DomainEvents", "DomainEvents", "Stores domain events")

System(adminPanel, "Admin Panel", "Admin Panel for managing the system")
System(reportPanel, "Report Panel", "Report Panel for analytics and data from the system")

Rel(delegate, CDN, "Uses", "HTTPS")
Rel(exhibitor, CDN, "Uses", "HTTPS")
Rel(speaker, CDN, "Uses", "HTTPS")

Rel(delegate, mobileApplication, "Uses", "HTTPS")
Rel(exhibitor, mobileApplication, "Uses", "HTTPS")
Rel(speaker, mobileApplication, "Uses", "HTTPS")

Rel(CDN, spaApplication, "Origin", "HTTPS")
Rel(webApplication, spaApplication, "Publish", "HTTPS")

Rel(mobileApplication, backend, "Uses", "HTTPS, REST API")

Rel(spaApplication, backend, "Uses", "HTTPS, REST API")
Rel(backend, database, "Insert/Update/Read", "TCP/SQL")

Rel(admin, adminPanel, "Uses", "HTTPS")
Rel(adminPanel, backend, "CRUD", "HTTPS, REST API")

Rel(analyst, reportPanel, "Uses", "HTTPS")
Rel(reportPanel, domainEvents, "Queries", "DomainEvents")
Rel(database, domainEvents, "Emits", "DomainEvents, JSON structure")
Rel(reportPanel, backend, "Queries", "HTTPS, REST API")

SHOW_LEGEND()
@enduml
