@startuml DelegateRegistration

header Delegate Event Registration Sequence Diagram

actor Delegate
participant "SessionService" as SS
participant "EventService" as ES

group Login
Delegate -> SS: POST /login
activate SS
SS -> SS: check credentials
SS -> Delegate: send session token
deactivate SS
end

group Register for event
Delegate -> ES: GET /events
activate ES
ES -> ES: get all events
ES -> Delegate: send list of events
deactivate ES
Delegate -> ES: POST /registerEvent 
activate ES
ES -> ES: check registration form
ES -> ES: add delegate to event
ES -> Delegate: send confirmation
deactivate ES
end

@enduml
